Add `/v1/breached` endpoint support on `user-intel` service.
pangeacyber/pangea-python pull request #545
Opened 2024-11-26 12:52 UTC by pangea-andrest

2024-11-26 17:17 UTC, kenany commented on packages/pangea-sdk/pangea/asyncio/services/intel.py
> +        return await self.request.post("v1/breached", m.BreachedResult, data=input.model_dump(exclude_none=True))
In LVE I see `v1/breach`.

2024-12-19 16:01 UTC, kenany requested changes
Still has some minor review comments and now a merge conflict.

2024-12-19 17:15 UTC, pangea-andrest commented
@kenany Updated!

2024-12-20 18:17 UTC, kenany requested changes

2024-12-20 18:17 UTC, kenany commented on CHANGELOG.md
> +- `/v1/breach` endpoint support on `user-intel` service.
Need to go under `## Unreleased` now.

2024-12-28 22:57 UTC, kenany approved these changes

2024-12-28 22:57 UTC, merged